A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
	path('', views.detail, name='detail'),
	path('add/<int:product_id>/', views.cart_add, name='cart_add'),
	path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
	path('create/', views.order_create, name='create'),
	path('<int:order_id>/', views.detail, name='detail'),
	path('payment/<int:order_id>/<price>/', views.payment, name='payment'),
	path('verify/', views.verify, name='verify'),
	path('apply/<int:order_id>/', views.coupon_apply, name='coupon_apply'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


class CartAddForm(forms.Form):
	quantity = forms.IntegerField(min_value=1, max_value=9)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .cart import Cart
from shop.models import Product
from .forms import CartAddForm
from django.views.decorators.http import require_POST


def detail(request):
	cart = Cart(request)
	return render(request, 'cart/detail.html', {'cart':cart})

@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product, quantity=cd['quantity'])
	return redirect('cart:detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:detail')

cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}

<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Unit Price</th>
        <th scope="col">Total Price</th>
        <th scope="col">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td><a href="{% url 'cart:cart_remove' item.product.id %}">Remove</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td>Total</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price }}</td>
    </tr>
    </tbody>
</table>

    <a href="{% url 'orders:create' %}" class="btn btn-primary">Checkout</a>

{% endblock %}